In [25]:
!python pytorch/setup.py install

running install
/home/wangchenjun/.conda/envs/NNRT/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/wangchenjun/.conda/envs/NNRT/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing nn_cuda.egg-info/PKG-INFO
writing dependency_links to nn_cuda.egg-info/dependency_links.txt
writing top-level names to nn_cuda.egg-info/top_level.txt
reading manifest file 'nn_cuda.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'nn_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/home/wangchenjun/.conda/envs/NNRT/lib/python3.8/site-packages/torch/utils/cpp_extension.py:782:

In [26]:
!python python/main2.py

Running cuda...
Cuda time:  41.127us
Running torch...
Torch time:  44.751us
tensor([0.8383, 0.1594, 0.1952,  ..., 0.9980, 0.8150, 0.3366], device='cuda:0')
tensor([0.5347, 0.7128, 0.4732,  ..., 0.3062, 0.2928, 0.8278], device='cuda:0')
tensor([1.3729, 0.8722, 0.6684,  ..., 1.3043, 1.1078, 1.1644], device='cuda:0')


In [27]:
!git add .
!git commit -m "auto update"
!git push origin master

[master c8d5ee9] auto update
 5 files changed, 277 insertions(+), 128 deletions(-)
 create mode 100644 .ipynb_checkpoints/notebook-checkpoint.ipynb
 create mode 100644 .vscode/settings.json
 rewrite kernel/add2_kernel.cu (68%)
 create mode 100644 notebook.ipynb
对象计数中: 11, 完成.
Delta compression using up to 12 threads.
压缩对象中: 100% (9/9), 完成.
写入对象中: 100% (11/11), 3.41 KiB | 872.00 KiB/s, 完成.
Total 11 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:WangChenjun521/nn_cuda.git
   905386e..c8d5ee9  master -> master
