In [49]:
%%capture
!python pytorch/setup.py install

In [50]:
!python python/main2.py

Running cuda...
Cuda time:  41.080us
Running torch...
Torch time:  44.703us
tensor([0.5963, 0.1389, 0.6208,  ..., 0.5762, 0.7781, 0.1635], device='cuda:0')
tensor([0.1870, 0.9347, 0.5460,  ..., 0.6332, 0.0193, 0.9252], device='cuda:0')
tensor([0.7833, 1.0735, 1.1668,  ..., 1.2094, 0.7973, 1.0887], device='cuda:0')


In [33]:
# !git status
# !git add .
# !git commit -m "auto update"
# !git push origin master